### ISSUE TITLE
What's the meaning of normal in your data?

### ISSUE THREAD

**Issue by LZleejean** [junxuan-li/LRG_360Panoramic#1]
In my knowledge, the floor's normal of normal map is (0.5, 1.0, 0.5). It means that it's view normal is (0.0, 1.0, 0.0). We set +y as up direction.
But in your synthetic data, the floor's normal is (0.2, 1.0, 0.2). Is your normal defined in view space?

**Comment by junxuan-li** [comment]
Please look at the ground truth normal map at : "LRG_360Panoramic/data/synthetic/barbershop/normal_gt.npy" for example.
The floor's normal is (0.0, 1.0, 0.0).

**Comment by LZleejean** [comment]
> Please look at the ground truth normal map at : "LRG_360Panoramic/data/synthetic/barbershop/normal_gt.npy" for example.
> The floor's normal is (0.0, 1.0, 0.0).

Thank you for your reply. The ".npz" file is right.
